### PR TITLE
fix: support event data json w/o compact format

### PR DESCRIPTION
**Pull request by yehudi-beseye**
support event data json w/o compact format

<a href="https://gitpod.io/#https://github.com/pahud/cdk-lambda-bash/pull/265"></a>

### CODE REVIEW

**Comment by pahud** [comment]
LGTM. Yes we should have the bash variables double-quoted.

**Comment by pahud** [comment]
copy @neilkuan

**Review by pahud — APPROVED** [review]

**Comment by pahud** [comment]
Hi @yehudi-beseye  can you run `yarn test` to update the snapshots again and commit again?

**Comment by neilkuan** [comment]
Great

**Comment by yehudi-beseye** [comment]
change snapshop

**Review by neilkuan — APPROVED** [review]

**Comment by pahud** [comment]
ship it!!

**Pull request merged**
